#!/bin/bash
export USER=bytesized
export HOME=/config
export DISPLAY=:0

if [ ! -d /config/.vnc ]; then
  mkdir -p /config/.vnc
fi

echo "Setting VNC passwd"
echo "$1" | vncpasswd -f > /config/.vnc/passwd
chmod 600 /config/.vnc/passwd

# Supervisor should start it automatically after this.
echo "Killing VNC and restarting it"
vncserver -kill :0
