#!/bin/bash
export USER=bytesized
export HOME=/config
export DISPLAY=:0

echo "Starting VNC"

if [ ! -f /config/.vnc/passwd ]; then
  /app/set_password "abcdefgh"
fi

vncserver :0 -geometry 1280x800 -name connect-vnc
sleep 3
xfconf-query --channel xfce4-desktop --property /backdrop/screen0/monitor0/image-path --set /app/Wallpaper-1.png

tail -f /config/.vnc/*.log
